version: '3'
services:
  web:
    build: .
    ports:
      - "127.0.0.1:8080:3000"
    depends_on:
      - db
    command: rails s -p 3000 -b '0.0.0.0'

  db:
    restart: always
    image: mysql:8.0
    ports:
      - "127.0.0.1:13306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
